// Auto-generated by LexiAI
// Last sync: $(date)
window.lexiaiData = $(cat dictionary.json);

// Make it available globally
if (typeof window.lexiai !== 'undefined') {
  window.lexiai.loadFromData(window.lexiaiData);
}

console.log('📚 LexiAI dictionary loaded:', window.lexiaiData.metadata.totalWords, 'words');
